CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fio varchar NOT NULL,
    age smallint NOT NULL CHECK (age > 14 and age < 150),
    passport_details varchar NOT NULL UNIQUE,
    phone_number varchar(11) NOT NULL UNIQUE,
    email varchar NOT NULL UNIQUE,
    password varchar NOT NULL
);

INSERT INTO users (fio, age, passport_details, phone_number, email, password) VALUES ('Иванов Иван Иванович', 24, '123123123 pass', '89999999999', 'ivan@mail.ru', '$2a$05$t5.51FMLI7JbPtvRYK1Fhu9.3K6wHlM0BGtQOE6cQlnuwxA02KyaW');
INSERT INTO users (fio, age, passport_details, phone_number, email, password) VALUES ('Петров Пётр Калыванович', 41, '456456456 pass', '89315342451', 'petya@mail.ru', '$2a$05$t5.51FMLI7JbPtvRYK1Fhu9.3K6wHlM0BGtQOE6cQlnuwxA02KyaW');
INSERT INTO users (fio, age, passport_details, phone_number, email, password) VALUES ('Анисин Владимир Владимирович', 20, '789789789 pass', '89531920111', 'vova@mail.ru', '$2a$05$t5.51FMLI7JbPtvRYK1Fhu9.3K6wHlM0BGtQOE6cQlnuwxA02KyaW');
